version: "3.9"

services:
  app:
    build: .
    container_name: orphancenter_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: orphancenter_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: orphancenter_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: